# Generated by Django 2.0.7 on 2018-07-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ValidIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('units', models.CharField(choices=[('ea', 'item'), ('ml', 'millilitre'), ('g', 'grams')], max_length=2)),
                ('classification', models.ManyToManyField(to='ingredients.Type')),
            ],
        ),
        migrations.AddField(
            model_name='useringredients',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ValidIngredients'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ValidIngredients'),
        ),
        migrations.AddField(
            model_name='diet',
            name='exclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.Type'),
        ),
    ]
