# Generated by Django 2.0.7 on 2018-07-28 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('expiry', models.DateField(null=True)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValidIngredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('units', models.CharField(choices=[('ea', 'item'), ('ml', 'millilitre'), ('g', 'grams')], max_length=2)),
                ('classification', models.ManyToManyField(to='ingredients.Type')),
            ],
        ),
        migrations.AddField(
            model_name='useringredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ValidIngredients'),
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingredients.ValidIngredients'),
        ),
        migrations.AddField(
            model_name='diet',
            name='exclusion',
            field=models.ManyToManyField(to='ingredients.Type'),
        ),
    ]
