# Generated by Django 2.0.7 on 2018-07-28 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='belongs_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ingredients.Recipe'),
            preserve_default=False,
        ),
    ]
