# Generated by Django 2.0.7 on 2018-07-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='exclusion',
        ),
        migrations.AddField(
            model_name='diet',
            name='exclusion',
            field=models.ManyToManyField(to='ingredients.Type'),
        ),
    ]
