# Generated by Django 2.0.7 on 2018-07-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_recipeingredients_belongs_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='text',
            new_name='ingredient',
        ),
    ]
