# Generated by Django 2.0.7 on 2018-07-28 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0003_auto_20180728_2045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
        migrations.RenameModel(
            old_name='UserIngredients',
            new_name='UserIngredient',
        ),
        migrations.RenameModel(
            old_name='ValidIngredients',
            new_name='ValidIngredient',
        ),
    ]
    atomic = False